# Generated by Django 5.0.12 on 2025-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=50)),
                ('appointment_type', models.CharField(choices=[('In-Person', 'In-Person'), ('Virtual', 'Virtual'), ('Emergency', 'Emergency'), ('Follow-Up', 'Follow-Up'), ('Routine Checkup', 'Routine Checkup')], default='In-Person', max_length=50)),
            ],
        ),
    ]
