# Generated by Django 5.0.12 on 2025-02-26 18:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK', unique=True)),
                ('emergency_contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('doctor_attending', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('insurance_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_insurance', to='billing.insurance')),
            ],
        ),
    ]
