# Generated by Django 5.0.12 on 2025-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=10)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer'), ('Insurance', 'Insurance')], default='Cash', max_length=20)),
                ('insurance_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('coverage_details', models.TextField()),
                ('co_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
            ],
        ),
    ]
