# Generated by Django 5.0.12 on 2025-03-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_billitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
