# Generated by Django 5.0.12 on 2025-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_bill_patient_remove_payment_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(choices=[('Doctor Appointment', 'Doctor Appointment'), ('Lab Test', 'Lab Test'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
