# Generated by Django 5.1.6 on 2025-05-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(choices=[('Doctor Appointment', 'Doctor Appointment'), ('Lab Test', 'Lab Test')], default='Other', max_length=20),
        ),
    ]
