# Generated by Django 5.0.12 on 2025-02-26 18:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(auto_now_add=True)),
                ('diagnosis_detail', models.TextField(blank=True, null=True)),
                ('tests_ordered', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('speciality', models.CharField(max_length=100)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK', unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('availability', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=80)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('shift_timings', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('medication_detail', models.TextField(blank=True, null=True)),
                ('dosage', models.TextField(blank=True, null=True)),
                ('refill_count', models.IntegerField(default=0)),
                ('prescription_till_date', models.DateField()),
                ('medication_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Nurse', 'Nurse'), ('Technician', 'Technician'), ('Receptionist', 'Receptionist'), ('Administrator', 'Administrator'), ('Billing', 'Billing')], max_length=50)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK', unique=True)),
                ('shift_timings', models.CharField(max_length=50)),
                ('date_hired', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
