# Generated by Django 5.0.12 on 2025-04-04 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
