# Generated by Django 5.0.12 on 2025-04-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtest_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_date',
            field=models.DateTimeField(),
        ),
    ]
