# Generated by Django 5.1.7 on 2025-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_labtest_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
