# Generated by Django 5.1.6 on 2025-05-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_labtest_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_date',
            field=models.DateField(),
        ),
    ]
