# Generated by Django 5.0.12 on 2025-02-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_registration',
            field=models.BooleanField(default=False),
        ),
    ]
