# Generated by Django 5.0.12 on 2025-03-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_has_completed_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_completed_registration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_member',
        ),
    ]
